Суркис Антон, домашняя работа 1
asurkis/sem10-formal-lang-course pull request #2
Opened 2023-02-28 11:18 UTC by asurkis

Прошу проверить всю вторую домашнюю работу.

- [x] Используя возможности [pyformlang](https://pyformlang.readthedocs.io/en/latest/) реализовать **функцию** построения минимального ДКА по заданному регулярному выражению. [Формат регулярного выражения.](https://pyformlang.readthedocs.io/en/latest/usage.html#regular-expression).
- [x] Используя возможности [pyformlang](https://pyformlang.readthedocs.io/en/latest/) реализовать **функцию** построения недетерминированного конечного автомата по [графу](https://networkx.org/documentation/stable/reference/classes/multidigraph.html), в том числе по любому из графов, которые можно получить, пользуясь функциональностью, реализованной в [Задаче 1](https://github.com/FormalLanguageConstrainedPathQuerying/formal-lang-course/blob/main/tasks/task1.md) (загруженный из набора данных по имени граф, сгенерированный синтетический граф). Предусмотреть возможность указывать стартовые и финальные вершины. Если они не указаны, то считать все вершины стартовыми и финальными.
- [x] Добавить необходимые тесты.

2023-02-28 15:49 UTC, rustam-azimov requested changes

2023-02-28 15:49 UTC, rustam-azimov commented on project/finite_automatons.py
> +    dfa = nfa.to_deterministic()
Проверьте. Это кажется лишним.

2023-02-28 15:49 UTC, rustam-azimov commented on project/finite_automatons.py
> +def regex_to_dfa(expr: str) -> DeterministicFiniteAutomaton:
К каждой функции теперь пишите пожалуйста документацию. Входные параметры, что делает и что возвращает.

2023-02-28 15:49 UTC, rustam-azimov commented on project/finite_automatons.py
> +def graph_to_nfa(g: nx.MultiDiGraph) -> NondeterministicFiniteAutomaton:
Нету возможности указывать стартовые и конечные вершины.

2023-02-28 15:52 UTC, asurkis commented on project/finite_automatons.py
> +    dfa = nfa.to_deterministic()
Что именно проверить? Если речь про `minimize()` (который в комментарий не попал), то проверял, без него получается не минимальный конечный автомат.

2023-02-28 20:48 UTC, asurkis commented on project/finite_automatons.py
> +def regex_to_dfa(expr: str) -> DeterministicFiniteAutomaton:
Написал документацию для функций этого домашнего задания

2023-02-28 20:48 UTC, asurkis commented on project/finite_automatons.py
> +def graph_to_nfa(g: nx.MultiDiGraph) -> NondeterministicFiniteAutomaton:
Исправил

2023-02-28 20:50 UTC, asurkis commented on project/finite_automatons.py
> +def regex_to_dfa(expr: str) -> DeterministicFiniteAutomaton:
Добавил документацию к функциям.

2023-02-28 20:50 UTC, asurkis commented on project/finite_automatons.py
> +def graph_to_nfa(g: nx.MultiDiGraph) -> NondeterministicFiniteAutomaton:
Добавил возможность указывать стартовые и конечные вершины.

2023-03-01 07:30 UTC, rustam-azimov commented on project/finite_automatons.py
> +    dfa = nfa.to_deterministic()
nfa.to_deterministic() является лишней строчкой, проверьте в документации minimize функции

2023-03-01 07:33 UTC, asurkis commented on project/finite_automatons.py
> +    dfa = nfa.to_deterministic()
А, да, действительно. Исправил.

2023-03-01 07:34 UTC, rustam-azimov approved these changes

2023-03-01 07:35 UTC, merged