Суркис Антон, домашняя работа 8
asurkis/sem10-formal-lang-course pull request #7
Opened 2023-04-14 13:01 UTC by asurkis

- [x] Реализовать **функцию**, основанную на алгоритме Хеллингса, решающую задачу достижимости между всеми парами вершин для заданного графа и заданной КС грамматики.
  - Результат работы функции --- множество троек вида (вершина, нетерминал, вершина).
  - Предусмотрите возможность получать граф из различных источников в различных форматах.
  - Предусмотрите возможность получать грамматику из различных источников (из файла, как результат работы других функций).
  - Для преобразования грамматики в ОНФХ использовать результаты предыдущих работ.
- [x] На основе предыдущей функции реализовать функцию, позволяющую решать задачу достижимости для заданного набора стартовых и финальных вершин, и заданного нетерминала.
- [x] Добавить необходимые тесты.

2023-04-16 07:49 UTC, rustam-azimov requested changes

2023-04-16 07:49 UTC, rustam-azimov commented on project/graphs.py
> +def hellings(cfg: CFG, graph: nx.MultiDiGraph) -> Set[Tuple]:
Предусмотрите также разные форматы для графов и грамматики. Например чтение из файла, текст.

2023-04-16 11:56 UTC, asurkis commented on project/graphs.py
> +def hellings(cfg: CFG, graph: nx.MultiDiGraph) -> Set[Tuple]:
Добавил

2023-04-18 09:32 UTC, rustam-azimov approved these changes

2023-04-18 09:33 UTC, merged